### ISSUE TITLE
Does not work with MusixMatch

### ISSUE THREAD

**Issue by ghost** [Maxr1998/XMediaNotificationTrackSelector#1]
Log below
01-12 10:13:12.086 E/Xposed  ( 1159): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
01-12 10:13:12.086 E/Xposed  ( 1159):   at de.Maxr1998.xposed.mnts.TrackSelector$1.beforeHookedMethod(TrackSelector.java:56)
01-12 10:13:12.086 E/Xposed  ( 1159):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
01-12 10:13:12.086 E/Xposed  ( 1159):   at android.widget.RemoteViews.performApply(<Xposed>)
01-12 10:13:12.086 E/Xposed  ( 1159):   at android.widget.RemoteViews.apply(RemoteViews.java:2770)
01-12 10:13:12.086 E/Xposed  ( 1159):   at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:1575)
01-12 10:13:12.086 E/Xposed  ( 1159):   at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:1976)
01-12 10:13:12.086 E/Xposed  ( 1159):   at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1867)
01-12 10:13:12.086 E/Xposed  ( 1159):   at com.android.systemui.statusbar.BaseStatusBar$7$2.run(BaseStatusBar.java:563)
01-12 10:13:12.086 E/Xposed  ( 1159):   at android.os.Handler.handleCallback(Handler.java:739)
01-12 10:13:12.086 E/Xposed  ( 1159):   at android.os.Handler.dispatchMessage(Handler.java:95)
01-12 10:13:12.086 E/Xposed  ( 1159):   at android.os.Looper.loop(Looper.java:148)
01-12 10:13:12.086 E/Xposed  ( 1159):   at android.app.ActivityThread.main(ActivityThread.java:5470)
01-12 10:13:12.086 E/Xposed  ( 1159):   at java.lang.reflect.Method.invoke(Native Method)
01-12 10:13:12.086 E/Xposed  ( 1159):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-12 10:13:12.086 E/Xposed  ( 1159):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-12 10:13:12.086 E/Xposed  ( 1159):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

**Comment by ghost** [comment]
Sorry I did not read the description properly. Closing this issue.

**Comment by Maxr1998** [comment]
ok, no prob ;)

**Comment by Maxr1998** [comment]
I updated this app some time ago that it doesn't show the button for players which don't support the track selector.
