### ISSUE TITLE
Could you support kitkat?

### ISSUE THREAD

**Issue by What-Zit-Tooya** [Maxr1998/XMediaNotificationTrackSelector#2]
would be nice if you support it

**Comment by Maxr1998** [comment]
Probably not, as there are lots of APIs missing in KitKat. For example, before Lollipop, music players had to use a custom layout for their notification, now there is a MediaStyle notification which makes it possible for me to hook the notifications globally. Without that, I had to include support for every music player out there independently, which just isn't possible for me.
