### ISSUE TITLE
Scroll to current track

### ISSUE THREAD

**Issue by GautierLePire** [Maxr1998/XMediaNotificationTrackSelector#3]
Hello,

I would like, when I open the playlist, that it scrolls to the playing track. (Like what GPM does in the Now Playing panel)

Thank you in advance for your answer.

(Also, is it possible to tint GPM completely with XGPM or only the buttons?)

**Comment by Maxr1998** [comment]
Actually, it already scrolls to the current track. But it doesn't scroll back to it when you scrolled away, closed and reopened the panel. Of course, when switching to a new track, it will scroll again.

**Comment by GautierLePire** [comment]
It doesn't work on my phone (bq Aquaris M5, 5.1.1)

What happens:
- When I do nothing, it shows the top of the list
- When I scroll, close, open, it shows where I was
- When a new track starts, it returns to the top

Thank you

**Comment by Maxr1998** [comment]
@thegeeex I guess you're using Timber?
I may have to ask the dev to implement that feature.

**Comment by GautierLePire** [comment]
Here is a screencast of the bug.
https://vid.me/uqLO
I'm using GPM with old notification design (thanks to XGPM)

Thank you

Also, something I've never noticed, it doesn't display album covers.

**Comment by Maxr1998** [comment]
Ok, I see. Could you make sure you're running the latest version of XGPM and this app?

**Comment by GautierLePire** [comment]
I use:
XGPM v1.8.4 (02/20/2016)
XMNTS v1.1.1 (02/02/2016)

**Comment by Maxr1998** [comment]
Ok, thanks. It seems the newest GPM broke the Track Selector anyway (for GPM), so I will fix this issue in one go. I'll report back when it works again.

**Comment by Maxr1998** [comment]
Ah, now I understand. Upgrade to XMNTS 1.1.2 from 02/08/2016, and you'll have the feature.
