### ISSUE TITLE
White flash when closing track selector

### ISSUE THREAD

**Issue by GautierLePire** [Maxr1998/XMediaNotificationTrackSelector#7]
There is a white flash when the track selector is closed.

**Comment by Maxr1998** [comment]
About your other (previously main) issue, please file the report at XGPM issue tracker. Thanks.

**Comment by Maxr1998** [comment]
I already know how to fix this problem, stay tuned.

**Comment by Maxr1998** [comment]
Fixed in 1.1.3.
